---
title: "About"
description: "A place for ramblings and reflections."
sidebar: false
page-layout: article
toc: true
---

## Who I am

I am a PhD Candidate in History at the University of Cambridge, studying intergenerational memory construction and place-making among British Ugandan Asians from 1972 to the present day. I have a first-class BA Hons. in History from the University of Exeter and a distinction in MA World History and Cultures from King's College London.  

Before I was an academic, I was an artist. The smartest thing I do day to day is let myself a little time outside to see the sun, feel the rays on my face, watch a raindrop curve down the petal of a struggling flower. Before LinkedIn, there were ladybirds and lollipops and lakes; there was the great, beautiful, awesome swathes of the ocean and the feel of sand between my toes. A place for thoughts, observations, creations and everything in-between. I want to be weird and wonderful! Welcome!

## What I write about

**Nature** — notes on the natural world. From epic and awesome landscapes to the veins of a garden leaf, and everything inbetween. 

**Music** — for all my musical fascinations. Album and song recommendations to broader commentary on the industry.

**History** — essays on my historical interests, including and beyond my project. A combination of my academic exploits and late-night rabbit hole obsessions.

**Travel** — a diary of my travels. From interesting details to broad observations on some of the places I've been and wish to go.

**Arts** — responses to visual art, literature and film. 

## How to reach me

If you would like to get in touch with me about my project or other thoughts, feel free to contact me at srj45@cam.ac.uk. 
